[project]
name = "my-frame-granian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioredis>=2.0.1",
    "fastapi>=0.122.0",
    "redis>=6.2.0",
]
